quarkus:
  http:
    port: 8090

  datasource:
    db-kind: postgresql
    username: postgres
    password: test1234
    jdbc:
      url: jdbc:postgresql://localhost:5432/studentcrm

  liquibase:
    migrate-at-start: true
    change-log: db/changeLog-root.yaml